spring.application.name=demo

game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3

game.connectfour.default-player-count=2
game.connectfour.default-board-size=7

game.taquin.default-player-count=1
game.taquin.default-board-size=4

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=mysql

user-service.url=http://localhost:8081
# http://localhost:8080/swagger-ui.html

jwt.secret=ma-cle-secrete-tres-longue-pour-mon-jwt-123456